spring:
  application:
    name: Poc - Jasper Reports
  profiles:
    active: dev

config:
  activate:
    on-profile: dev

app:
  message: This is the main property file fo the ${spring.application.name}
  api:
    context: api/${app.api.version}/
    version: v1
  template:
    jasper:
      location: templates/jasper/

